package com.mobileshop.enums;

public enum CategoryType {
	//Car
	CONVERTIBLE, COMBI, COUPE, SEDAN, HATCHBACK, JEEP, MINIVAN,
	//Bus
	HEARSE, PASSENGER, AMBULANCE, FREIGHT, WAGON,
	//Truck
	AVTOVOZ, TRACTOR, CRANE, MULTILIFT, SNOWPLOUGH, CISTERN,
	//Motor
	ATV, CAFERACER, UTV, CROSS, SLEDGECAR, TRACK, SCOOTER, TRICYCLE, CHOPPER, TURRET,
	//Agro
	HARROW, BALING, ROLLER, HARVESTER, CULTIVATOR, MULCHER, PLOUGH, SPRAYER, MOWER, SEEDER, MILLER, HEDER, CHISEL,
	//CARAVAN
	CARAVAN, CAMPER;
}
